// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

struct DateTime {
  int year;
  int month;
  int day;
  int hour;
  int minute;
};

void initProperties(){

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);

